FROM python:3.6.2

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install build-essential curl
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y nodejs
RUN nodejs -v && npm -v

# Requirements have to be pulled and installed here, otherwise caching won't work
ADD requirements.txt /reactlibapp/
ADD . /reactlibapp/

WORKDIR /reactlibapp
RUN pip3 install -r requirements.txt && cd /reactlibapp/client/ && npm install && npm run build-development

# create user and add to docker group
RUN adduser --disabled-password --gecos '' djangoreactapp
RUN groupadd docker
RUN usermod -aG docker djangoreactapp

# set permission on files for docker sake
RUN chown -R djangoreactapp:$(id -gn djangoreactapp) ~/
RUN chown -R djangoreactapp:$(id -gn djangoreactapp) ~/
RUN chown -R djangoreactapp:$(id -gn djangoreactapp) /reactlibapp/
ENV PYTHONUNBUFFERED 1

RUN chmod +x ./run_web.sh && chmod +x ./launch.sh
USER djangoreactapp

ENTRYPOINT ["./run_web.sh"]
